management:
  endpoints:
    web:
      exposure:
        include: '*'
#logging:
#  level:
#    root: INFO
#  file:
#    name: ./logs/myapp.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
